//For Gate Product
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_SINGLE_REQUEST = "GET_SINGLE_REQUEST";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const GET_SINGLE_FAILURE = "GET_SINGLE_FAILURE";

// Review
// create
export const CREATE_REVIEW_REQUEST ="CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS ="CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_FAIL ="CREATE_REVIEW_FAIL"




// Delete
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";



// Edit
export const EDIT_REVIEW_REQUEST = "EDIT_REVIEW_REQUEST";
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS";
export const EDIT_REVIEW_FAIL = "EDIT_REVIEW_FAIL";

// get

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";
