//For Gate Product
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_SINGLE_REQUEST = "GET_SINGLE_REQUEST";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const GET_SINGLE_FAILURE = "GET_SINGLE_FAILURE";


export const POST_CART_REQUEST = "GET_SINGLE_REQUEST";
export const POST_CART_SUCCESS = "GET_SINGLE_SUCCESS";
export const POST_CART_FAILURE = "GET_SINGLE_FAILURE";

