export const POST_CART_REQUEST = "POST_CART_REQUEST";
export const POST_CART_SUCCESS = "POST_CART_SUCCESS";
export const POST_CART_FAILURE = "POST_CART_FAILURE";

export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";



export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";



export const REMOVE_CART_REQUEST = "REMOVE_CART_REQUEST";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_FAILURE = "REMOVE_CART_FAILURE";

export const REMOVE_ALL_CART_REQUEST = "REMOVE_ALL_CART_REQUEST";
export const REMOVE_ALL_CART_SUCCESS = "REMOVE_ALL_CART_SUCCESS";
export const REMOVE_ALL_CART_FAILURE = "REMOVE_ALL_CART_FAILURE";


export const EDIT_CART_REQUEST = "EDIT_CART_REQUEST";
export const EDIT_CART_SUCCESS = "EDIT_CART_SUCCESS";
export const EDIT_CART_FAILURE = "EDIT_CART_FAILURE";